import type { EmployeeNewWizardFormValues } from "./EmployeeNewWizard.types";

export const EMPLOYEE_NEW_WIZARD_DEFAULT_VALUES: EmployeeNewWizardFormValues = {
  firstName: "",
  lastName: "",
  middleName: "",
  dateOfBirth: "",
  gender: "",
  civilStatus: "",
  nationality: "Filipino",
  placeOfBirth: "",
  addressLine1: "",
  addressLine2: "",
  city: "",
  province: "",
  zipCode: "",
  personalEmail: "",
  mobileNumber: "",
  emergencyContactName: "",
  emergencyRelationship: "",
  emergencyContactNumber: "",
  employeeId: "EMP-00091",
  department: "",
  position: "",
  employmentType: "",
  dateHired: "",
  workLocation: "",
  shiftSchedule: "",
  sssNumber: "",
  philHealthNumber: "",
  pagIbigNumber: "",
  tin: "",
  basicSalary: "",
  payFrequency: "",
  taxExemption: "",
  sendInvite: true,
  role: "",
};
